### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/secret-agent-chat#1]
Hi @lauraclay or @LornaLynch - could I get a copy edit on this, sometime this week. No urgency.
Thanks

**Comment by LornaLynch** [comment]
@lauraclay do you want me to take some of this or are you ok?

**Comment by lauraclay** [comment]
Just finished it now :)

**Comment by MarcScott** [comment]
Thank you - lightning fast again. Much appreciated
